### ISSUE TITLE
How to get the latest tag?

### ISSUE THREAD

**Issue by 030** [al4/docker-registry-list#1]
Instead of returning a list, would it be possible to do something like this?

```
./docker-registry-list.py ubuntu | grep bionic-.* | tail -n1 | sed "s|.*\"\(.*\)\".*|\1|g"
bionic-20190515
```

Basically, I would like to issue `./docker-registry-list.py ubuntu bionic` and then `bionic-20190515` has to be returned.

**Comment by al4** [comment]
You could do this in python, but unfortunately the docker list API doesn't give a way to get the latest by date - it sorts lexically. This might give the right result in many repositories, but as you have shown, not ubuntu, because the codenames wrap.

So unfortunately the short answer is, not really - any code to do this would be specific to the repository.

The "right" way to do this, if you always want the latest release, is to pull the "latest" tag. By convention this should always point at the most recent release. Presumably, the "bionic" tag also points at the most recent bionic release.
